# Site settings
title: CRU
email: cydoval@ucdavis.edu
description: > # this means to ignore newlines until "baseurl:"
  The Computing Resources Unit at the College of Agricultural and Environmental Sciences at UC Davis is one helluva mouthful.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://computing.caes.ucdavis.edu" # the base hostname & protocol for your site

permalink: pretty

paginate: 3

# Build settings
markdown: kramdown

#gems
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-autoprefixer
  - jekyll-redirect-from

collections:
  ace:
    output: true
    permalink: /documentation/:collection/:title
  purchasing:
    output: true
    permalink: /documentation/:collection/:title
  policies:
    output: true
    permalink: /documentation/:collection/:title
  helpdesk:
    output: true
    permalink: /documentation/:collection/:title
  peaks:
    output: true
    permalink: /documentation/:collection/:title
  commencement:
    output: true
    permalink: /documentation/:collection/:title
  payments:
    output: true
    permalink: /documentation/:collection/:title
  registration:
    output: true
    permalink: /documentation/:collection/:title
  harvest:
    output: true
    permalink: /documentation/:collection/:title
  portfolio:
  team:
  screenshots:
collections_dir: collections

defaults:
  - scope:
      type: "helpdesk"
    values:
      categories: "helpdesk"
      brand: "helpdesk"
      documentation: "aside"
      layout: "twocol"
      bio: "true"
  - scope:
      type: "policies"
    values:
      categories: "policies"
      brand: "policies"
      documentation: "aside"
      layout: "twocol"
      bio: "true"
  - scope:
      type: "purchasing"
    values:
      categories: "purchasing"
      brand: "purchasing"
      documentation: "aside"
      layout: "twocol"
      bio: "true"
  - scope:
      type: "ace"
    values:
      categories: "ace"
      brand: "ace"
      documentation: "aside"
      layout: "twocol"
      bio: "true"
  - scope:
      type: "peaks"
    values:
      categories: "peaks"
      brand: "peaks"
      documentation: "aside"
      layout: "twocol"
      bio: "true"
  - scope:
      type: "commencement"
    values:
      categories: "commencement"
      brand: "commencement"
      documentation: "aside"
      layout: "twocol"
      bio: "true"
  - scope:
      type: "payments"
    values:
      categories: "payments"
      brand: "payments"
      documentation: "aside"
      layout: "twocol"
      bio: "true"
  - scope:
      type: "registration"
    values:
      categories: "registration"
      brand: "registration"
      documentation: "aside"
      layout: "twocol"
      bio: "true"

breadcrumbs:
root:
  hide: false # show breadcrumbs on root/home page
  image: false # Show image or title text
